# Generated by Django 3.1.3 on 2020-11-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='topic',
            new_name='content',
        ),
    ]
